version: '3.9'

networks:
  hehe:
    name: hehe

services:
  ca.superadmin.com:
    container_name: ca.superadmin.com
    image: hyperledger/fabric-ca:1.5.4
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.superadmin.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    volumes:
      - ./fabric-ca:/etc/hyperledger/fabric-ca-server
    networks:
      - hehe
