version: '3.9'

volumes:
  peer.producer0.com:

networks:
  hehe:
    name: hehe

services:
  peer.producer0.com:
    container_name: peer.producer0.com
    image: hyperledger/fabric-peer:2.4.5
    working_dir: /root
    command: peer node start
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
#      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.producer0.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer.producer0.com
      - CORE_PEER_ADDRESS=peer.producer0.com:5054
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5054
      - CORE_PEER_CHAINCODEADDRESS=peer.producer0.com:5055
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5055
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.producer0.com:5054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.producer0.com:5054
      - CORE_PEER_LOCALMSPID=Producer0MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer.producer0.com:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hehe
    volumes:
      - ./peers:/etc/hyperledger/fabric
      - peer.producer0.com:/var/hyperledger/production
      - ./peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - "5054:5054"
      - "9447:9447"
    networks:
      - hehe
    depends_on:
      - couchdb.producer0.com
