version: '3.9'

networks:
  hehe:
    name: hehe

services:
  ca.producer0.com:
    container_name: ca.producer0.com
    image: hyperledger/fabric-ca:1.5.4
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.producer0.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7052
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17052
    ports:
      - "7052:7052"
      - "17052:17052"
    volumes:
      - ./fabric-ca:/etc/hyperledger/fabric-ca-server
    networks:
      - hehe
