version: '3.9'

networks:
  hehe:
    name: hehe

services:
  couchdb.distributor0.com:
    container_name: couchdb.distributor0.com
    image: couchdb:3.2.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5954:5984"
    networks:
      - hehe
